apiVersion: v1
kind: Service
metadata:
  labels:
    app: kibana
    release: kibana
  name: kibana-kibana-public
  namespace: logging
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # Specify NLB
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"  # Public Load Balancer
spec:
  ports:
  - name: http
    port: 5601
    protocol: TCP
    targetPort: 5601
  selector:
    app: kibana
    release: kibana
  type: LoadBalancer
status:
  loadBalancer: {}